version: '3.8'

services:
  web:
    build: .
    container_name: biletgo-app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./database:/var/www/html/database
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped
